### ISSUE TITLE
path: does not work

### ISSUE THREAD

**Issue by ArminJo** [Legion2/download-release-action#6]
Hi Leon,
I use your action
```
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: ArminJo/Arduino-BlueDisplay
          tag: '1.3.0'
          path: /home/runner/Arduino/libraries
```
 but I cannot find the result files
```
Archive:  download.tmp
   creating: Arduino-BlueDisplay-1.3.0/
   creating: Arduino-BlueDisplay-1.3.0/.github/
...
```
      - name: test 
        run: |
          echo "List /home/runner/Arduino/libraries"
          ls -l /home/runner/Arduino/libraries
gives:
```
Run echo "List /home/runner/Arduino/libraries"
List /home/runner/Arduino/libraries
ls: cannot access '/home/runner/Arduino/libraries': No such file or directory
```
Grüße aus Köln
Armin
